#!/usr/bin/env bash
# a bash script that displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=$'\n' read -r line; do
        echo "$line" | awk -F: '{printf "The user %s is part of the %s gang, lives in %s and rides %s. %s'\''s place is protected by the passcode %s, more info about the user here: %s\n", $1, $4, $6, $7, $3, $2, $5}'
done <<< "$(cat /etc/passwd)"
