#!/usr/bin/env bash
# a bash script that displays the visitor IP along with the HTTP status code from the Apache log file
awk '{printf "%s %s\n", $1, $9}' ./apache-access.log | sort | uniq -c | sort -nr
