#!/usr/bin/env bash
# This script is displaying Best School 10 times
counter=0
end=10
while [ "$counter" -le "$end" ]; do
    if [ "$counter" -eq 9 ]; then
	    echo Hi
    else
	    echo Best\ School
    fi
    ((counter++))
done
