#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

counter=0
counter2=1

while [ "$counter" -le 12 ]; do
	echo Hour:\ $counter
	while [ "$counter2" -lt 60 ]; do
		echo $counter2
		((counter2++))
	done
	counter2=1
	((counter++))
done

